### ISSUE TITLE
Inventory rollback: Items not added to armor and off-hand slots

### ISSUE THREAD

**Issue by magne37** [PlayPro/CoreProtect#170] opened 2022-03-11 22:15 UTC
If you rollback a player's inventory, and that player's inventory was full including armor and off-hand, then some of the full slots in that player's inventory will get deleted to make space for the armor and off-hand items. Therefore that player could lose valuable items.

To replicate:
1. Make your inventory full, with armor and off-hand filled
2. Clear inventory or get rid of items
3. Rollback your inventory

Version: 21.1

**Comment by Intelli** [comment] 2022-03-11 22:18
CoreProtect won’t/can’t delete items to add items. The issue is likely just that the inventory is being seen as full and items just aren’t being added.

**Comment by Intelli** [comment] 2022-03-12 00:24
Fixed here: https://github.com/PlayPro/CoreProtect/commit/3011aece46e347dc35c6d068030b1975e5593479

Fix will be included in v21.2. I've also attached a patched v21.1 version with the fix for you.

[CoreProtect-21.1b.jar.zip](https://github.com/PlayPro/CoreProtect/files/8236630/CoreProtect-21.1b.jar.zip)

**Closed** 2022-03-21 22:44 UTC
Labels: bug
