### ISSUE TITLE
Container Info - API Suggestion

### ISSUE THREAD

**Issue by lukemango** [PlayPro/CoreProtect#107] opened 2021-11-09 16:50 UTC
I'd really like to see a way to get container info (all the info currently shown in /co i) but available through the API.

**Comment by bbeeland** [comment] 2021-11-09 16:50
This should be a thing.

**Comment by Internal-Exception** [comment] 2021-11-09 20:05
Yes please!

**Comment by Intelli** [comment] 2021-11-09 21:04
Duplicate of #91

**Closed** 2023-07-13 21:57 UTC
Labels: duplicate, suggestion, accepted
