### ISSUE TITLE
Please update your plugin on 1.20 version😇😇😇

### ISSUE THREAD

**Issue by RaweeY** [PlayPro/CoreProtect#394] opened 2023-06-25 22:28 UTC
Please update your plugin on 1.20.I and my server players wait this update.Your plugin best in this segment and very comfortable!Me and my players would be happy If you do it as soon as possible.Thanks in advance!

**Comment by globau** [comment] 2023-06-28 05:24
Duplicate of #378

**Closed** 2023-07-13 21:54 UTC
Labels: duplicate
