### ISSUE TITLE
[SUGGESTION] Compatibility with SF?

### ISSUE THREAD

**Issue by RealmKebab** [PlayPro/CoreProtect#495] opened 2024-01-22 07:30 UTC
Looking up for Slimefun items using CoreProtect is a MASSIVE pain in the ass, since you need to look at some type of vanilla ingot tags & player heads which is mess to even do.
This could help me out a lot since one of our (it's run by the staff team) server relies heavily on slimefun and without it, we wouldn't be getting the players we would've normally had

**Comment by vacla** [comment] 2024-01-22 11:36
Duplicate of #390

**Closed** 2024-01-22 15:52 UTC
