### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by SrMonsterYT** [PlayPro/CoreProtect#334] opened 2023-03-09 20:40 UTC
There are many plugins that have this configuration:

1° https://prnt.sc/pMZ1JqHdDfaZ
2° https://prnt.sc/dP-w3cPS_VV9

in your configuration, can you define 1 X day to delete files so you don't have to program it to execute the /co purge command, this would help a lot, I don't understand how this amazing plugin doesn't have this option yet

**Comment by Intelli** [comment] 2023-03-09 20:44
Duplicate of #176

**Comment by SrMonsterYT** [comment] 2023-03-09 20:46
sorry I didn't see that I already had a suggestion I will delete it and comment there

**Closed** 2023-03-09 20:47 UTC
Labels: duplicate
