### ISSUE TITLE
Boats & Hoppers not being logged

### ISSUE THREAD

**Issue by RobellaMC** [PlayPro/CoreProtect#360] opened 2023-04-23 20:03 UTC
Boats being placed, broken, or accessed is not being logged. Hopper movement is also not being logged, but nothing is disabled in the config. Using the most up to date version of core protect.

**Comment by Intelli** [comment] 2023-04-25 19:20
Duplicate of #232 

For hopper movement, you probably have `disable-move-event` enabled: https://docs.papermc.io/paper/reference/world-configuration#disable-move-event

**Closed by Intelli** 2023-04-25 19:20 UTC
Labels: duplicate

**Comment by RobellaMC** [comment] 2023-04-27 20:02
I do not have disable-move-event enabled. The issue is still persisting.

**Comment by Intelli** [comment] 2023-04-27 20:03
Please ensure you're using the latest version of CoreProtect, Paper, and don't have any conflicting plugins installed on your server.

Note that hopper actions are displayed on the attached containers, not the hoppers themselves.
