### ISSUE TITLE
Could not pass event AsyncChatEvent to coreprotect v20.2

### ISSUE THREAD

**Issue by Frowley95** [PlayPro/CoreProtect#121] opened 2021-12-18 11:28 UTC
A few seconds after someone writes a message in the chat (atleast I believe that is the cause), I get this error:

[07:33:01] [Async Chat Thread - #21/ERROR]: Could not pass event AsyncChatEvent to CoreProtect v20.2
java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/plain/PlainTextComponentSerializer
	at net.coreprotect.paper.listener.PaperChatListener.onPlayerChat(PaperChatListener.java:17) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor356.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-786]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-786]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Paper-786]
	at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:130) ~[patched_1.16.5.jar:git-Paper-786]
	at io.papermc.paper.adventure.ChatProcessor.lambda$process$1(ChatProcessor.java:68) ~[patched_1.16.5.jar:git-Paper-786]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:120) ~[patched_1.16.5.jar:git-Paper-786]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2102) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2017) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1955) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) ~[patched_1.16.5.jar:git-Paper-786]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by vacla** [comment] 2021-12-18 12:43
This is a duplicate of #120

**Closed** 2021-12-18 18:34 UTC
Labels: duplicate
