### ISSUE TITLE
1.20 sign edits

### ISSUE THREAD

**Issue by JHarris12345** [PlayPro/CoreProtect#405] opened 2023-07-11 00:43 UTC
In 1.20 you can edit signs by right clicking them. It seems that sign edits cannot be rolled back

**Comment by o7q** [comment] 2023-07-11 03:29
CoreProtect has not been updated to 1.20 yet.

**Comment by Intelli** [comment] 2023-07-13 21:53
Duplicate of https://github.com/PlayPro/CoreProtect/issues/384

**Closed by Intelli** 2023-07-13 21:53 UTC
