### ISSUE TITLE
Core Protect error on moving written signs with world edit 

### ISSUE THREAD

**Issue by Momshroom** [PlayPro/CoreProtect#386] opened 2023-06-16 18:54 UTC
When I select a written sign and move it (tested with wall and floor signs of various woods with plain text on them) with world edit with core protect installed, I get the following error:
`[18:22:07 INFO]: Momshroom issued server command: //hpos1                    
[18:22:09 INFO]: KaoKoKong issued server command: /cinfo
[18:22:10 INFO]: Momshroom issued server command: //hpos2
[18:22:17 INFO]: KaoKoKong issued server command: /cpersist
[18:22:18 INFO]: Momshroom issued server command: //move 1
[18:22:18 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.DyeColor.
[18:22:18 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:273)                                                                                   
[18:22:18 WARN]:        at org.bukkit.DyeColor.valueOf(DyeColor.java:11)
[18:22:18 WARN]:        at CoreProtect-21.3.jar//net.coreprotect.worldedit.WorldEditLogger.postProcess(WorldEditLogger.java:76)
[18:22:18 WARN]:        at CoreProtect-21.3.jar//net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:52)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:45)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:281)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.EditSession.close(EditSession.java:882)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:540)                             
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51)[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:390)
[18:22:18 WARN]:        at worldedit-bukkit-7.2.15.jar//com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55)
[18:22:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[18:22:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:933)
[18:22:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[18:22:18 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[18:22:18 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[18:22:18 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[18:22:18 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2298)
[18:22:18 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2258)
[18:22:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[18:22:18 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:22:18 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18) 
[18:22:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[18:22:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[18:22:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[18:22:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1425)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[18:22:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[18:22:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

When core protect is NOT installed, there is no error moving the same signs.

In either case, the sign moves properly.

Tested with paper 1.20.1 #28 and #31.  Error occurs on both.

Worldedit version 7.2.15+6463-5ca4dff

CoreProtect 21.3

Java 17

**Comment by Momshroom** [comment] 2023-06-16 18:56
Here's the error as a paste instead so easier to read:
https://paste.gg/p/Momshroom/f42e67686eea4347bd02dfc1073e1dbc

**Comment by ByteExceptionM** [comment] 2023-06-21 21:41
Same problem here!

```
[21:53:22] [AsyncNotifyQueue - 0/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.DyeColor.
[21:53:22] [AsyncNotifyQueue - 0/WARN]: 	at java.base/java.lang.Enum.valueOf(Enum.java:273)
[21:53:22] [AsyncNotifyQueue - 0/WARN]: 	at org.bukkit.DyeColor.valueOf(DyeColor.java:11)
[21:53:22] [AsyncNotifyQueue - 0/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.worldedit.WorldEditLogger.postProcess(WorldEditLogger.java:76)
[21:53:22] [AsyncNotifyQueue - 0/WARN]: 	at CoreProtect-21.3.jar//net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:52)
```

**Comment by mrfloris** [comment] 2023-06-22 05:10
Cannot reproduce this in FAWE, but regular worldedit seems to have this issue.

**Comment by Intelli** [comment] 2023-07-13 21:54
Fixed in https://github.com/PlayPro/CoreProtect/commit/4e43a42662fe84351ae718478f23870cb6b84425#diff-6173fe645435519fc6e494359729a29250267ce0ebcb530c284af6be087d3539

**Closed by Intelli** 2023-07-13 21:54 UTC
