### ISSUE TITLE
[Problem] Server TPS Dipping to 4 - 12TPS on rollback

### ISSUE THREAD

**Issue by uwuw7** [PlayPro/CoreProtect#100] opened 2021-10-31 03:40 UTC
EVERY time I rollback any big area or amount of time now the server drops to 4 TPS and kicks everyone because of it. Watchdog reports it and the server basically perm crashes

**Comment by Intelli** [comment] 2021-10-31 08:15
Duplicate of your other issue - #99

If there’s an error, please include it in your bug report.

**Closed by Intelli** 2021-10-31 08:15 UTC
