### ISSUE TITLE
Problem with teleportation on distant coordinates

### ISSUE THREAD

**Issue by Imperatr1ce** [PlayPro/CoreProtect#322] opened 2023-01-28 14:43 UTC
When we are trying to automatically teleport according to the list (screenshot) to large coordinates, it teleport us to coordinate z:1 

![image](https://cdn.discordapp.com/attachments/466533948374253589/1068885763246268458/123.png)

**Comment by Intelli** [comment] 2023-01-28 18:16
As far as I’m aware, 1.44684815E7 is not a valid coordinate. Numbers in scientific notation are not supported.

1.44 is interpreted as 1, which is intended behaviour.

**Comment by Imperatr1ce** [comment] 2023-01-28 18:39
The CoreProtect plugin, when clicking on the **/co lookup list**, automatically fills in coordinates and teleports the player to them, but in this case, the coordinates x835094/y-42/z14468481 **are represented as** x: 835094 y: -42 z: 1.44684815E7, not like that 835094 -42 14468481.
Because of this player teleports incorrectly

**Comment by vacla** [comment] 2023-01-28 18:59
This is a valid issue, see following image 
![Screenshot_20230128_195828_Chrome](https://user-images.githubusercontent.com/10290022/215285984-d9f3ad2b-65c6-45e3-ae6d-db3d36bd16c5.jpg)

This is the exact number they had, and if you parse to double it changes to that.

**Comment by Intelli** [comment] 2024-01-05 03:10
Fixed in https://github.com/PlayPro/CoreProtect/commit/74240377954caee13c26b9999f60d6570d0263a7

**Closed by Intelli** 2024-01-05 03:10 UTC
Labels: bug
