### ISSUE TITLE
Suggestion: Add a hover event that shows an item's display name

### ISSUE THREAD

**Issue by JHarris12345** [PlayPro/CoreProtect#283] opened 2022-08-23 18:27 UTC
So for logs that show if an item was dropped, removed from a container etc. I think if you hover over where it says, for example, "1x Netherite Sword", it should show the swords display name (or just repeat Netherite Sword if it doesn't have one)

**Comment by vacla** [comment] 2022-08-23 18:39
See: #221

**Comment by JHarris12345** [comment] 2022-08-23 20:43
Do we know know when that will be in the main release?

**Comment by vacla** [comment] 2022-08-23 20:47
I got no clue, intelli needs to merge this, there are a few other branch that needs to be merged still for next release

**Comment by Intelli** [comment] 2022-12-10 19:07
Duplicate of https://github.com/PlayPro/CoreProtect/issues/67.

**Closed** 2024-05-08 19:31 UTC
Labels: duplicate, suggestion
