### ISSUE TITLE
[Suggestion] allow filtering for purges

### ISSUE THREAD

**Issue by jarekt** [PlayPro/CoreProtect#38] opened 2021-07-12 13:32 UTC
It would be very helpful if the same filtering parameters that are available in co lookup/rollback/restore could be used to filter what to purge, so you could for example purge only stuff by `user:#piston` to get rid of database spam from flying machines or purge mob drops from a radius (a specific farm).

**Comment by Intelli** [comment] 2021-07-14 01:59
Duplicate of #4

**Closed by Intelli** 2021-07-14 01:59 UTC
