### ISSUE TITLE
value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by arima0k** [PlayPro/CoreProtect#287] opened 2022-09-07 23:09 UTC
This error appears in console, almos random (when some players join).

```
[06:05:17 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:05:17 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:05:17 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:05:17 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:05:17 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:05:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:05:28 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:05:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:05:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:05:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:05:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:05:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:05:38 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:05:38 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:05:38 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:05:38 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:05:38 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:05:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:05:54 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:05:54 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:05:54 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:05:54 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:05:54 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:05:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:26:05 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:26:05 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:26:05 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:26:05 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:26:05 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:26:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:26:16 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:26:16 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:26:16 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:26:16 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:26:16 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:26:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:26:28 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
[06:26:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
[06:26:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
[06:26:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
[06:26:28 WARN]:        at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[06:26:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Intelli** [comment] 2022-12-07 23:35
Duplicate of #261 / #293

**Closed** 2022-12-08 00:50 UTC
Labels: bug, duplicate
